refactored to read all options prior to setting up discretizations
TDycores-Project/TDycore pull request #97
Opened 2020-10-09 23:09 UTC by ghammond86

2020-10-10 01:44 UTC, bishtgautam commented
@ghammond86 Can you describe the change? Are demos now not allowed to call `TDySetFromOptions()`?

2020-10-10 05:12 UTC, ghammond86 commented
Prior to this refactor, the initialization of TDycore many objects (discretization, matrices, vectors, etc.) was intermingled with the reading of options.  This poses a problem when command line options override default settings programmed into the demos.  The refactor ensures that all command line options are read and parsed prior to creating objects.  Demos may call TDySetFromOptions() prior to TDySetup(), but TDySetFromOptions() is automatically called within TDySetup().

2020-10-10 05:16 UTC, bishtgautam commented
Why not force the demos to call only `TDySetup()`?

2020-10-10 06:03 UTC, ghammond86 commented
The demos do only call TDySetip().

Glenn

On Oct 9, 2020, at 10:17 PM, Gautam Bisht <notifications@github.com> wrote:

﻿

Why not force the demos to call only TDySetup()?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTDycores-Project%2FTDycore%2Fpull%2F97%23issuecomment-706490264&data=02%7C01%7Cglenn.hammond%40pnnl.gov%7C22f9b1cc0ccd469b045208d86cdbbab6%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637379038270274472&sdata=vwT6yl9TdbSqDUwwWhyG3d4LQXocAhmAqEjI5umRMnE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEBJFKOM37UBCKCMBPP3XVLSJ7U43ANCNFSM4SKT5OYA&data=02%7C01%7Cglenn.hammond%40pnnl.gov%7C22f9b1cc0ccd469b045208d86cdbbab6%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637379038270274472&sdata=nBW%2FMYcjzw7Ouu77DM1xDfWS0cpPTVDCGsDqRT4JCHI%3D&reserved=0>.

2020-10-10 14:33 UTC, jedbrown reviewed
Is this fixing the issue where fields were being created based on the default discretization?

2020-10-10 21:27 UTC, bishtgautam commented
@ghammond86 In that case, let's get rid of `TDSetFromOptions()` from [tdycore.h](https://github.com/TDycores-Project/TDycore/blob/glenn/refactor-options/include/tdycore.h#L77) and the equivalent Fortran interfaces.

2020-10-10 21:28 UTC, bishtgautam requested changes
Remove TDSetFromOptions() from tdycore.h and the equivalent Fortran interfaces.

2020-10-12 17:37 UTC, ghammond86 commented on demo/steady/steady.c
> +#endif
PetscViewer is required by the subsequent viewers below the #if 0 block.  I removed the block to clean up the code.

2020-10-12 17:42 UTC, ghammond86 commented on src/tdycore.c
> +  // must come after TDySetFromOptions()
This was a comment from an intermediate commit.  Squashing with rebase does not make this evident as the history is destroyed.  I have remove it.

2020-10-12 17:45 UTC, ghammond86 commented on demo/steady/steady.c
> +#endif
I believe that the PR resolves the issue of fields being created off the default discretization, but I would need an example problem to compare before and after.

2020-10-12 19:16 UTC, bishtgautam approved these changes

2020-10-12 19:18 UTC, bishtgautam commented
@ghammond86 Why do the gold files need to be updated for TPF?

2020-10-12 19:35 UTC, ghammond86 commented
> @ghammond86 Why do the gold files need to be updated for TPF?

The TPF was using the MPFA_O matrix, which had extra columns (with zeros) than the standard star stencil.  During ILU factorization, those factored entries seemed to be tweaking the answer ever so slightly.  I ran comparisons with Jacobi (diagonal only) and direct LU preconditioning and the extra column and standard star stencil matrices matched.  What I do not understand is that the results for ILU (with extra columns and standard star) did not match Jacobi preconditioning or direct LU.  But I had to move on.  I trust the results as the matrices had identical values.

2020-10-12 19:36 UTC, merged